--CREATE TABLE SYS_USER (
--UUID BIGINT(10) NOT NULL AUTO_INCREMENT COMMENT '',
--USER_NAME VARCHAR(20) NULL DEFAULT NULL COMMENT '用户名',
--PASSWORD VARCHAR(64) NULL DEFAULT NULL COMMENT '密码',
--PRIMARY KEY (UUID)
--) ENGINE=INNODB DEFAULT CHARSET=UTF8

CREATE TABLE sys_user  (
  UUID bigint(10) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  USER_NAME VARCHAR(20) NULL DEFAULT NULL COMMENT '用户名',
  PASSWORD VARCHAR(64) NULL DEFAULT NULL COMMENT '密码',
  PRIMARY KEY (UUID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;