server:
  port: 8099

logging:
  config:

spring:
  datasource:
    master:
      jdbc-url: jdbc:h2:mem:modeltestdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=1;MODE=MySQL
      driverClassName: org.h2.Driver
    slave1:
      jdbc-url: jdbc:h2:mem:modeltestdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=1;MODE=MySQL
      driver-class-name: org.h2.Driver
    slave2:
      jdbc-url: jdbc:h2:mem:modeltestdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=1;MODE=MySQL
      driver-class-name: org.h2.Driver
